/**
 * Types for volumetric terrain system with Marching Cubes
 */

/**
 * Mesh data generated by marching cubes algorithm
 */
export interface IMeshData {
  positions: Float32Array; // Vertex positions (x, y, z, x, y, z, ...)
  normals: Float32Array; // Vertex normals (nx, ny, nz, ...)
  colors: Float32Array; // Vertex colors (r, g, b, r, g, b, ...)
  indices: Uint32Array; // Triangle indices
  vertexCount: number;
  triangleCount: number;
}

/**
 * A volumetric chunk containing density field and mesh data
 */
export interface IVolumetricChunk {
  key: string; // "x_y_z" format (e.g., "0_0_0", "100_-80_0")
  worldX: number; // World X position (corner of chunk)
  worldY: number; // World Y position (corner of chunk)
  worldZ: number; // World Z position (corner of chunk)
  densityField: Float32Array; // 3D density values (negative = solid, positive = air)
  meshData: IMeshData | null; // Generated mesh, null if chunk is empty or fully solid
  isEmpty: boolean; // True if chunk is entirely air (no surface)
  isSolid: boolean; // True if chunk is entirely solid (no surface)
  createdAt: number; // Timestamp for cache management
}

/**
 * Chunk coordinate in chunk space (not world space)
 */
export interface IChunkCoord {
  x: number; // Chunk X index
  y: number; // Chunk Y index
  z: number; // Chunk Z index
}

/**
 * Loaded volumetric chunk with additional runtime data
 */
export interface ILoadedVolumetricChunk extends IVolumetricChunk {
  lastAccessedAt: number; // For LRU cache eviction
}

/**
 * Configuration for volumetric terrain generation
 */
export interface IVolumetricConfig {
  chunkSize: number; // World units per chunk (X and Z)
  chunkHeight: number; // World units per chunk (Y)
  resolution: number; // Voxels per world unit
  isoLevel: number; // Density threshold for surface (typically 0)
  caveEnabled: boolean; // Enable cave generation
  caveThreshold: number; // Cave noise threshold
  caveFrequency: number; // Cave noise frequency
  minCaveHeight: number; // Minimum Y for caves
  maxCaveHeight: number; // Maximum Y for caves
}

/**
 * Density sampling function signature
 */
export type DensityFunction = (
  worldX: number,
  worldY: number,
  worldZ: number,
) => number;

/**
 * Color sampling function signature (for vertex coloring)
 */
export type ColorFunction = (
  worldX: number,
  worldY: number,
  worldZ: number,
) => { r: number; g: number; b: number };
